services:
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=smartdb
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=priv4te
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
  
  web:
    image: victorffernandes/smart-attendance-bff:latest
    restart: always
    command: python app/manage.py migrate && python app/manage.py runserver 0.0.0.0:8000
    pull_policy: always
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
    links:
      - db
    depends_on:
      - db