version: "2"
services:
  db:
    image: mysql:8
    container_name: smartdb
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=priv4te
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - /opt/docker/smartattendance/volumes/mysql:/var/lib/mysql

  web:
    image: victorffernandes/smart-attendance-bff:latest
    restart: on-failure
    container_name: smartweb
    command: sh ./docker/start.sh
    ports:
      - "8000:8000"
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
    depends_on:
      - db
