services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=smartdb
      - POSTGRES_USER=mysql_user
      - POSTGRES_PASSWORD=priv4te
  web:
    image: victorffernandes/smart-attendance-bff:latest
    pull_policy: always
    command: python app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=smartdb
      - POSTGRES_USER=mysql_user
      - POSTGRES_PASSWORD=priv4te
    depends_on:
      - db