# Generated by Django 4.2.5 on 2023-10-06 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma_nome', models.CharField(max_length=60)),
                ('semestre', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(max_length=60)),
                ('usuario_tipo', models.CharField(choices=[('A', 'Aluno'), ('P', 'Professor')], max_length=1)),
                ('id_externo', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Turma_Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Seg', 'Segunda'), ('Ter', 'Terça'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sábado')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartattendance.turma')),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartattendance.usuario'),
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_entrada', models.DateTimeField()),
                ('tempo_saida', models.DateTimeField()),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartattendance.usuario')),
                ('chamada_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartattendance.chamada')),
            ],
        ),
        migrations.AddField(
            model_name='chamada',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartattendance.turma'),
        ),
        migrations.CreateModel(
            name='Aluno_Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartattendance.usuario')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartattendance.turma')),
            ],
        ),
    ]
