# Generated by Django 4.2.6 on 2023-10-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartattendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma_horario',
            name='hora_fim',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='turma_horario',
            name='hora_inicio',
            field=models.CharField(max_length=10),
        ),
    ]
